import type { NextPage } from "next";
import Head from "next/head";
import NextLink from 'next/link'
import s from "./Page.module.scss";
import Container from "../../components/Container/Index";

const Home: NextPage = () => {
  return (
    <div className={s.root}>
      <Head>
        <title>Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={s.main}>
        <Container>
          <h1>Example page to demonstrate routing</h1>
          <NextLink href="/" passHref>
            <a className={s.link}>Back to index page</a>
          </NextLink>
        </Container>
      </main>
    </div>
  );
};

export default Home;
