import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import s from "../styles/Home.module.scss";
import Container from "../components/Container/Index";
import NextLink from "next/link";
import HomeIcon from "@mui/icons-material/Home";
import HomeRoundedIcon from "@mui/icons-material/HomeRounded";
import { useAppDispatch, useAppSelector } from "../redux/hooks/redux";
import { cardSlice } from "../redux/store/reducers/CardSlice";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const { addCards, changeCategory } = cardSlice.actions;
  const { cards, activeCategory } = useAppSelector((state) => state.cardSlice);

  return (
    <div className={s.root}>
      <Head>
        <title>Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={s.main}>
        <Container>
          <a className={s.linkToHome} href="https://nikitavakula.vercel.app/">
            <HomeRoundedIcon fontSize="medium" />
          </a>
          {/* <button
            onClick={() => {
              dispatch(addCards());
            }}
          >
            fetch users
          </button> */}
          <h1>
            Next.js starter page
            <br /> includes:
          </h1>
          <ul className={s.includeList}>
            <li>Next.js, Typescript, Material UI, Redux Toolkit</li>
            <li>Favicon template</li>
            <li>Comfortable folder structure</li>
            {/* <li>Light/dark mode</li> */}
          </ul>

          <h1>To Do:</h1>
          <ul className={s.toDoList}>
            <li>
              Make options for the start page for the project on Chakra,
              Tailwind CSS, etc.
            </li>
            <li>RTC action create template</li>
          </ul>

          <NextLink href="/page" passHref>
            <a className={s.link}>Routing</a>
          </NextLink>
        </Container>
      </main>
    </div>
  );
};

export default Home;
